### ISSUE TITLE
Typescript Lint Errors

### ISSUE THREAD

**Issue by jamesgraves** [bonzaiferroni/bonzAI#12]
I recently ran the TypeScript lint task, and it mentioned about 1700 errors.

Will you be accepting patches to fix these sorts of things?  I can create pull requests that will only fix lint problems, and keep separate any new functionality or bug fixes that I have planned.

If you're not interested, you can just close this issue.

**Comment by bonzaiferroni** [comment]
hi James, I appreciate the offer. I actually started going through and fixing the lint errors myself, and I'm about 90% done. 

That code can be found under the "testing" branch which is actually fairly stable at the moment.

**Comment by jamesgraves** [comment]
Thanks. I'm giving the testing branch a try now.

I've started collecting issues I've been encountering here:

https://github.com/jamesgraves/bonzAI/issues

I could have submitted issues to your issues list instead, but I'm not expecting you to just fix them.  I'm expecting that I'll be trying to fix them myself, and maybe issuing pull requests.

Thanks again for creating bonzAI!
