### ISSUE TITLE
Nesting profiler calls

### ISSUE THREAD

**Issue by WesleyFudala** [bonzaiferroni/bonzAI#4]
Cpu time does not seem to be tracked properly when nesting profiler calls like so:

```
profiler.start("AllCreeps");
    profiler.start("FooCreeps");
    profiler.end("FooCreeps");

    profiler.start("BarCreeps");
    profiler.end("BarCreeps");
profiler.end("AllCreeps");
```

A potential fix could be to store the cpu per identifier 
ex: profiler.ts start() would do this:
```
if(!this[identifier]) this[identifier] = {};
this[identifier].cpu = Game.cpu.getUsed();
```
instead of this:
`this.cpu = Game.cpu.getUsed();`

**Comment by bonzaiferroni** [comment]
That is quite true about its inability to support nested calls, and that seems like a great way to handle it.

**Comment by bonzaiferroni** [comment]
I've refactored profiler.ts to be able to handle nested calls and also calls that happen sporadically (previously needed to be called every tick)
